const PLATFORMTYPE_GREYBOX = 3;
const PLATFORMTYPE_SMALL_BOX = 5;
const PLATFORMTYPE_PILLAR1 = 4;
const PLATFORMTYPE_PILLAR1_MOVING = 9;
const PLATFORMTYPE_HOLEWALL = 7;
const PLATFORMTYPE_HALFARCH_LEFT = 6;
const PLATFORMTYPE_HALFARCH_RIGHT = 8;