var playerpicright = new Image();
playerpicright.src = 'images/player2withgun.png'
var playerpicleft = new Image();
playerpicleft.src = 'images/player2withgun2.png'
var playerspritesheet1 = new Image();
playerspritesheet1.src = 'images/player2walkingwithgun11.png';
var playerspritesheet2 = new Image();
playerspritesheet2.src = 'images/player2walking21.png';
var playerspritesheet3 = new Image();
playerspritesheet3.src = 'images/player2climbing.png';
var playerpicclimbing = new Image();
playerpicclimbing.src = 'images/player2stillclimbing.png';
var grass = new Image();
grass.src = 'images/grass.png';
var gun1 = new Image();
gun1.src = 'images/gun1.png';
var startscreen = new Image();
startscreen.src = 'images/startscreen.png';
var drone1img = new Image();
drone1img.src = 'images/drone1.png';
var ladderimg = new Image();
ladderimg.src = 'images/ladder.png';
var sniperwalkingright = new Image();
sniperwalkingright.src = 'images/sniperswalkingright.png';
var controls = new Image();
controls.src = 'Images/controls.png';
var platformtop = new Image();
platformtop.src = 'Images/platformtop1.png';
var platformtop2 = new Image();
platformtop2.src = 'Images/platformtop2.png';
var platformright = new Image();
platformright.src = 'Images/platformside1.png';
var platformleft = new Image();
platformleft.src = 'Images/platformside2.png';
var background1 = new Image();
background1.src = 'Images/background1.png';
var escapepodpic = new Image();
escapepodpic.src = 'Images/escapepodsheet.png'
var playershootingleft = new Image();
playershootingleft.src = 'Images/player2shootingleft.png'
var drawing_gun_left = new Image();
drawing_gun_left.src = 'Images/player1/drawing_gun_left.png'
var drawing_gun_right = new Image();
drawing_gun_right.src = 'Images/player1/drawing_gun_right.png'
var shooting_left = new Image();
shooting_left.src = 'Images/player1/shooting_left.png'
var shooting_right = new Image();
shooting_right.src = 'Images/player1/shooting_right.png'
var walking_right = new Image();
walking_right.src = 'Images/player1/walking_right.png'
var walking_left = new Image();
walking_left.src = 'Images/player1/walking_left.png'
var walking_down = new Image();
walking_down.src = 'Images/player1/walking_down.png'
var standing_down = new Image();
standing_down.src = 'Images/player1/standing_down.png'
var walking_up = new Image();
walking_up.src = 'Images/player1/walking_up.png'
var standing_left = new Image();
standing_left.src = 'Images/player1/standing_left.png'
var standing_right = new Image();
standing_right.src = 'Images/player1/standing_right.png'
var box1_front = new Image();
box1_front.src = 'Images/NewFolder/box2_front.png'
var box1_back = new Image();
box1_back.src = 'Images/NewFolder/box2_back.png'
var barricade1 = new Image();
barricade1.src = 'Images/NewFolder/barricade.png'
var barricade2 = new Image();
barricade2.src = 'Images/NewFolder/barricade_front.png'
var barricade3 = new Image();
barricade3.src = 'Images/NewFolder/barricade_front_sheet1.png'
var barricade4 = new Image();
barricade4.src = 'Images/NewFolder/barricade_sheet1.png'
var bulletsheet1 = new Image();
bulletsheet1.src = 'Images/bulletred.png'
var bulletsheet2 = new Image();
bulletsheet2.src = 'Images/bulletgreen.png'
var bulletsheet4 = new Image();
bulletsheet4.src = 'Images/bulletpurple.png'
var bulletsheet3 = new Image();
bulletsheet3.src = 'Images/bomb1.png'
var wall1 = new Image();
wall1.src = 'Images/NewFolder/wall1.png'
var box1 = new Image();
box1.src = 'Images/NewFolder/box.png'
var floor_bottom = new Image();
floor_bottom.src = 'Images/NewFolder/floor_bottom.png'
var floorBase = new Image();
floorBase.src = 'Images/NewFolder/floorBase.png'
var ruins1 = new Image();
ruins1.src = 'Images/NewFolder/ruins1.png'
var floor1 = new Image();
floor1.src = 'Images/NewFolder/floor1.png'
var holewall1 = new Image();
holewall1.src = 'Images/NewFolder/holewall1.png'
var ruins2 = new Image();
ruins2.src = 'Images/NewFolder/ruins2.png'
var enemysheet1 = new Image();
enemysheet1.src = 'Images/NewFolder/enemysheet1.png'
var gun1 = new Image();
gun1.src = 'Images/NewFolder/gun1.png'
var gun2 = new Image();
gun2.src = 'Images/NewFolder/gun2.png'
var explosion1 = new Image();
explosion1.src = 'Images/NewFolder/explosion_sheet1.png'
var gun1pic = new Image();
gun1pic.src = 'Images/player1/gun1x2.png'
var gun2pic = new Image();
gun2pic.src = 'Images/player1/gun2x2.png'
var acidgun1 = new Image();
acidgun1.src = 'Images/NewFolder/acidgun.png'
var acidgun1pic = new Image();
acidgun1pic.src = 'Images/NewFolder/acidgun2x2.png'
var infinity = new Image();
infinity.src = 'Images/player1/infinity.png'
var zombie1 = new Image();
zombie1.src = 'Images/player1/zombie1.png'
var doorway1 = new Image();
doorway1.src = 'Images/NewFolder/doorway1.png'
var door1 = new Image();
door1.src = 'Images/NewFolder/door1.png'
var ammo1 = new Image();
ammo1.src = 'Images/player1/ammo1.png'
var doorway2 = new Image();
doorway2.src = 'Images/NewFolder/doorway2.png'
var ammocrate = new Image();
ammocrate.src = 'Images/NewFolder/ammocrate.png'
var medkitpic = new Image();
medkitpic.src = 'Images/NewFolder/medkit.png'
var lm14pic = new Image();
lm14pic.src = 'Images/NewFolder/lm14.png'
var wallbaseleft = new Image();
wallbaseleft.src = 'Images/NewFolder/wallbaseleft.png'
var wallbaseright = new Image();
wallbaseright.src = 'Images/NewFolder/wallbaseright.png'
var walltopmain = new Image();
walltopmain.src = 'Images/NewFolder/walltopmain.png'
var walltopright = new Image();
walltopright.src = 'Images/NewFolder/walltopright.png'
var weaponupgradefront = new Image();
weaponupgradefront.src = 'Images/NewFolder/weaponupgradefront.png'
var weaponupgradeback = new Image();
weaponupgradeback.src = 'Images/NewFolder/weaponupgradeback.png'